language: node_js
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.npm"
notifications:
  email: false
node_js:
- 8
script:
- "./node_modules/.bin/lerna bootstrap"
- "yarn build-all"
after_success:
- "./deploy.sh"